### ISSUE TITLE
Can this boot Windows 11?

### ISSUE THREAD

**Issue by kododake** [imbushuo/NintendoSwitchPkg#28]
Hi I'm currently wondering if I should build this.
Has anyone successfully booted Windows 11? If so, were you able to access the shell or desktop?
Thank you.

**Comment by officialmelon** [comment]
It boots into Windows 11 Installer no desktop yet

**Comment by kododake** [comment]
Why can't proceed from the installer? Is it a problem with touch, USB, etc.?

**Comment by officialmelon** [comment]
Has No Touch Support yet

**Comment by kododake** [comment]
Hopefully the touch feature will be supported someday.
Thank you for your reply.

**Comment by officialmelon** [comment]
(:
