### ISSUE TITLE
Empty screen after recent updates

### ISSUE THREAD

**Issue by myfreeweb** [imbushuo/NintendoSwitchPkg#5]
Hi, thanks for this project!

I've been able to run version d2b9bd6a68b926e43eab50b639726e67120c6d82 (and after fixing `if (sdmmc_storage_init_sd…)` → `if (!sdmmc_storage_init_sd…)` it even boots from SD, though I was getting weird page faults when booting FreeBSD — probably because of #3 MMU stuff that wasn't fixed then?)

Newer versions with the stuff ported from u-boot don't display anything on the screen, it lights up and stays blank :(

**Comment by imbushuo** [comment]
@myfreeweb Try latest commit, and make sure you have microSD inserted in.
Do you have UART access? If so, we can diagnose issues more easily.

**Comment by myfreeweb** [comment]
So the first non-working revision is 9e2a0f7 SDMMC: Take offline for bugfix. I just noticed that you changed the memory address of the framebuffer in that revision…

> UART access

Well, I have a very janky cable that used to mostly work and I don't remember which pin is what anymore… anyway, it would only show coreboot output, right?

**Comment by myfreeweb** [comment]
aaand yep, this brings it back:

```diff
--- i/NintendoSwitch.dsc
+++ w/NintendoSwitch.dsc
@@ -295,7 +295,7 @@
 
   # Display
   # Simple FrameBuffer
-  gNintendoSwitchPkgTokenSpaceGuid.PcdMipiFrameBufferAddress|0xdfb80000
+  gNintendoSwitchPkgTokenSpaceGuid.PcdMipiFrameBufferAddress|0xc0000000
   gNintendoSwitchPkgTokenSpaceGuid.PcdMipiFrameBufferWidth|768
   gNintendoSwitchPkgTokenSpaceGuid.PcdMipiFrameBufferHeight|1280
   gNintendoSwitchPkgTokenSpaceGuid.PcdMipiFrameBufferPixelBpp|32
```

**Comment by imbushuo** [comment]
@myfreeweb So I will go ahead and close this one.

For UART, I haven’t port the actual serial I/O library, but it should be an easy task. Currently you don’t see log in UEFI, it is normal.

**Comment by myfreeweb** [comment]
Does `0xdfb80000` work for you? interesting o_0
